### ISSUE TITLE
[Enhancement Request] - allow for larger Icon sizes on collapsed right-side menu

### ISSUE THREAD

**Issue by Truncated** [Dorako/pf2e-dorako-ui#321]
I'd like to have a control in the settings of UI for the collapsed sidebar (right side) to be able to increase the size of all of the icons uniformly. The larger icons would then revert to the "default" size when the panel is expanded.

Ideally the default would be as-is, with an option to match to the left side control icons or enter my own size number where minimum is the default size and max is constrained by the overall side height.

**Comment by Dorako** [comment]
As in something like this, but only when collapsed? 
![CleanShot 2024-07-01 at 18 13 01@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/fbf7526c-da39-4765-9e79-e9cea1b38594)

**Comment by Dorako** [comment]
Try playing around with this custom css and see if you get something you like:
```css
#ui-right > #sidebar.collapsed {
    --sidebar-tab-size: 48px;
    width: calc(var(--sidebar-tab-size) + 10px) !important; 
    padding-right: 5px; 
}
```
